### ISSUE TITLE
Add settings link in the plugins page

### ISSUE THREAD

**Issue by eentropy** [eentropy/WPTips-UpdateManager#2]
Add settings option in the plugin list page

**Comment by eentropy** [comment]
// Declarations
$plugin_basename = plugin_basename( __FILE__ );

// Include options
include 'WPTips-UpdateManager_options.php';

// Add settings link on plugin page
function UpdateManager_options_quicklink($links){
	$settings_link = '<a href="options-general.php?page=WPTips-UpdateManager.php">' . __( 'Settings' ) . '</a>';
	array_push( $links, $settings_link );
	return $links;
} 
add_filter("plugin_action_links_$plugin_basename",'UpdateManager_options_quicklink');

**Comment by eentropy** [comment]
There was a bug, FILE had to be with 2 underscores before and after

**Comment by Christian-98** [comment]
Yes, in fact the problem was the underscore. I tried our plugin and now it looks like the settings as we wanted, it keeps the variables settings also saved.
I attach the code change.

// Declarations
$plugin_basename = plugin_basename(__FILE__);

// Include options
include 'WPTips-UpdateManager_options.php';

// Add settings link on plugin page
function UpdateManager_options_quicklink($links){
	$settings_link = Link to settings; 
	array_unshift($links,$settings_link);
	return $connection;
} 
add_filter("plugin_action_links_$plugin_basename",'UpdateManager_options_quicklink');

**Comment by eentropy** [comment]
Closing issue, fixed and merged in base branch.
